spring:
  datasource:
    username: root
    password: tinysnow;
    url: jdbc:mysql://localhost:3306/?useUnicode=true&serverTimezone=UTC
      &characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

# 这里是对 SpringSecurity 的默认登陆页面进行验证所设的用户名和密码
#  security:
#    user:
#      name: user
#      password: tinysnow

  profiles:
    active: druid,mybatis